### ISSUE TITLE
How width and price intervals works?

### ISSUE THREAD

**Issue by pishangujeniya** [newbieeashish/Predict_the_cost_to_ship_sculptures_HackerEarth#1]
Can you please provide me with some information or literature which explains the theory of how `price_intervals` and `width_intervals` helps which you have calculated as a part of feature engineering works for your purpose?

**Comment by pishangujeniya** [comment]
![At least you should have helped](https://i.pinimg.com/originals/b2/de/7a/b2de7ada456562e834bd45c70e456770.jpg)

**Comment by newbieeashish** [comment]
It's a binning process when data is skewed

**Comment by pishangujeniya** [comment]
> It's a binning process when data is skewed

@newbieeashish  Thank You so much.

I am looking at the topic [https://towardsdatascience.com/feature-engineering-deep-dive-into-encoding-and-binning-techniques-5618d55a6b38](https://towardsdatascience.com/feature-engineering-deep-dive-into-encoding-and-binning-techniques-5618d55a6b38)
